import {Component} from '@angular/core'

@Component({
    template: `


        <div class="landing serif" style="font-size: 20px">
        <img style="display: block; margin: 0 auto;" src="assets/aapb-q-50jc.jpg">

            <p>
            The American Archive of Public Broadcasting (AAPB) is a rich collection of unique, non-commercial public media. The archive is maintained through a collaboration between PBS station WGBH in Boston and the Library of Congress. Since the project’s inception in 2013, the AAPB strives to collect and preserve radio and television programs created over the last 60 years. Currently more than 40,000 hours of programs created by over 100 public broadcasting stations have been digitized and made available for listening and viewing. Beyond this, over 2.5 million items have been inventoried for future digitization for this project. 
            </p>
            <p>
            American non-commercial media is immensely valuable for scholars, researchers, educators, institutions and organizations, as well as the general public. Educational and public media in this country has strived to serve the wide audiences across the nation with programming that produces knowledge to create an informed citizenry, or teaches life skills, or is hyper localized to the region which it serves. The value of aggregating and collecting this media information for posterity is beyond measure -- though the total investment that the American people have made in their public radio and television broadcasting stations since the 1960s is calculated at more than $10 billion. Preserving these radio and television programs is the media equivalent of preserving the country’s national parks.
            </p><p>
            The vast majority of the media items that have been tagged for processing and hosting by the AAPB are awaiting digitization, approximately 94% of the entire collection (or 2.35M items.) However all of these items have been catalogued using the archive’s PBCore metadata tagging system and are searchable online. Nearly 4% of the archive (~100k entries) have been digitized but, due to copyright concerns and legal clearances, these must be viewed at a research station at WGBH headquarters or the Library of Congress. This leaves 2% of the total programs within the archive (~50k items) that are available for listening and viewing in the archive’s Online Reading Room. This project deals specifically with those items.
            </p><p>
            <span class="views">Visually Exploring the American Archive of Public Broadcasting</span> is a tool for researchers and the general public to explore these fascinating contents through four visual expressions. The goal of this project is to broaden exposure to the work of the AAPB and highlight the value of publicly produced, non-commercial media. It is an exploratory interface for media and knowledge discovery.
            </p><p>
            Within the tool you will find two input fields: ‘search’ and ‘limit.’ Enter a search term to find entries within the archive that contain that term within their metadata. Limit or expand the number of results you would like to review by entering a value in the ‘limit’ field. Then choose your interface for visually interpreting the results:
            </p><p>
            <span class="views">Timeline:</span> A vertical histogram of entries by date. Each circle represents an entry and are arrayed in chronological order by year. 
            </p><p>
            <span class="views">Genre Cluster:</span> Each item within the AAPB has a metadata tag to represent the genres covered by the program. This view clusters together entries by shared dominant genre. 
            </p><p>
            <span class="views">Transcript:</span> Each item within the AAPB has an associated transcript that was generated by machine-learning voice-to-text technology. While the majority of the translation is correct, these transcripts still contain many errors. In order to reveal significance of the entry by determining the most commonly used words, a wordcloud is generated to highlight language usage within each media item. 
            </p><p>
            <span class="views">Map:</span> This view will show you where in the US the content was produced. Select a location and use the ‘next’ and ‘previous’ buttons at the top left to scroll multiple results. 
            </p><p>
            Each result pairs with the info panel seen at right, where a direct link to the archive item can be found so that users may review the media content directly. 
            </p>
        <p>
            <a [routerLink]="['search']" class="serif tool-link">
            Go to the visual search tool ...
            </a>  
            </p>

            <p style="padding: 50px 50px 50px 50px;"></p>
        </div>  
    `,
    styles: [`
        .header {
            width: 100%;
        }

        .landing {
            font-size: 14px;
            overflow: scroll;
            height: 100%;
            margin-bottom: 100px;
        }

        .landing p {
            margin: 0 auto;
            padding: 10px 10px 10px 10px;
            max-width: 950px;
        }

        .views {
            font-style: italic;
        }

        .tool-link {
            font-weight: bold;
            font-family: 'Lato';
            font-size: 20pt;
        }
    `]
})
export class LandingComponent {

}